version: '3.8'

x-project_environment: &project_environment
  PROJECT_NAME: ${PROJECT_NAME:-python_backend_template}
  ENVIRONMENT: ${ENVIRONMENT:-dev}
  DEBUG: ${DEBUG:-True}
  VAULT_HOST: ${VAULT_HOST:-"http://vault:8200"}
  VAULT_TOKEN: ${VAULT_TOKEN:-"vault-root-token"}
  VAULT_NAMESPACE: ${VAULT_NAMESPACE:-"service_name"}

services:
  app:
    build:
      context: .
    command: ["uvicorn", "--app-dir", "app/web", "--host", "0.0.0.0", "--reload", "main:fastapi_app"]
    expose:
      - 8000
    volumes:
      - ./:/service
    environment:
      <<: *project_environment
    labels:
      traefik.enable: true
      traefik.http.routers.api.entrypoints: web
      traefik.http.routers.api.rule: "Host(`api.docker.localhost`) &&  PathPrefix(`/`)"
      traefik.http.routers.api.service: api
      traefik.http.services.api.loadbalancer.server.port: 8000
      traefik.http.routers.api.tls: false
    depends_on:
      migrations:
        condition: service_completed_successfully
    env_file:
      - ./.env
    networks:
      - traefik

  migrations:
    build:
      context: .
    command: ["alembic", "upgrade", "head"]
    volumes:
      - ./:/service
    restart: no
    environment:
      <<: *project_environment
    env_file:
      - ./.env
    networks:
      - traefik


networks:
  traefik:
    driver: bridge
    external: true